### ISSUE TITLE
Input fasta is one line format.

### ISSUE THREAD

**Issue by gnilihzeux** [xiaofengsong/IRESfinder#3]
Hi, dear author. IRESfinder input fasta must be in one line for each entry, which you should add to your 'Readme', otherwise result will not consistent with your example.

such as
```
>id1
CCGAGGTC...TGC
```
but not
```
>id1
CCGAGGTC...
TGC
```

**Comment by zhaodoctor** [comment]
Thanks for reminding. We have modified the python scripts to make IRESfinder more compatible for fasta format files. Now,  the fasta format file that one id followed by multiple sequence lines can be processed by IRESfinder.
